// ── Columbia Road · AI Maturity Quiz Webhook ────────────────────────────────
// Paste this into Google Apps Script (script.google.com → New project)
// Deploy as a Web App: Execute as "Me", access "Anyone"
// Copy the deployment URL into APPS_SCRIPT_URL in index.html
// ─────────────────────────────────────────────────────────────────────────────

const SHEET_ID   = '1XRDP4UB_4Kbdzc_6KAitYoFxSHnuzVRpy7uh2oXsZ5o';
const SHEET_NAME = 'Sheet1';

// Column order in the sheet — one entry per key the quiz sends (index.html
// QUIZ_RESULT), so nothing is silently dropped and no column writes blank.
const COLUMNS = [
  'submitted_at',
  'name',
  'email',
  'role',
  'team_size',
  // Scoring v2 — readiness_score is already 0–100, so there is no separate pct
  'readiness_score',
  'readiness_band',
  'stage',
  'stage_index',
  'fit',
  'data_layer_pct',
  'context_layer_pct',
  'orchestration_layer_pct',
  'eval_obs_layer_pct',
  'weakest_area',
  'strongest_area',
  'points_to_next_band',
  'next_moves',
  'roi_estimate_eur',
  // Business context
  'deal_size',
  'close_rate',
  'admin_time',
  'monthly_leads',
  'lead_to_conv',
  'sales_process_docs',
  // AI maturity answers
  'ai_tools',
  'ai_agents',
  'ai_integration',
  'ai_scalability',
  'data_quality',
  'knowledge_source',
  'governance_owner',
  'sales_ai_contribution',
  'team_attitude',
  // Priorities
  'top_opportunities',
  'top_blockers',
  'biggest_time_waste',
  'roadmap_headline',
];

// Human-readable header labels. HEADERS[i] must label COLUMNS[i], then the four
// manual columns — several range reads size themselves off HEADERS.length.
const HEADERS = [
  'Submitted at',
  'Name',
  'Email',
  'Role',
  'Team size',
  'Readiness score /100',
  'Readiness band',
  'Stage',
  'Stage #',
  'Fit (foundations vs live)',
  'Data Layer %',
  'Context Layer %',
  'Orchestration Layer %',
  'Evaluation & Observation Layer %',
  'Weakest area',
  'Strongest area',
  'Points to next band',
  'Next moves',
  'ROI estimate (€)',
  'Deal size',
  'Close rate',
  'Admin time',
  'Monthly leads',
  'Lead → conv rate',
  'Sales process docs',
  'AI tools',
  'AI agents',
  'AI integration',
  'AI scalability',
  'Data quality',
  'Knowledge source',
  'Governance owner',
  'Sales AI contribution',
  'Team attitude',
  'Top opportunities',
  'Top blockers',
  'Biggest time waste',
  'Roadmap headline',
  // Filled in post-event by Claude Code
  'Email subject',
  'Email body',
  // Manual tracking
  'Email sent?',
  'Notes',
];

// Canonical label order for the aggregation. Must match STAGES / READY / FIT /
// DIMS in index.html — change there, change here. The dashboard derives colours
// positionally from these, so it never hardcodes a label itself.
const STAGE_ORDER = [
  'Stage 0: Nothing running yet',
  'Stage 1: Testing and pilots',
  'Stage 2: First agents live',
  'Stage 3: Several agents live',
];
const BAND_ORDER = ['Not there yet', 'Early days', 'Getting there', 'Ready for more', 'Solid ground'];
const FIT_ORDER  = ['ahead', 'matched', 'stretched'];
const DIM_ORDER  = ['Data Layer', 'Context Layer', 'Orchestration Layer', 'Evaluation & Observation Layer'];

// Dimension name → prompt-ready English, for the follow-up email.
const AREA_PHRASE = {
  'Data Layer':                    'the state of their customer and sales data',
  'Context Layer':                 'the company knowledge their AI can draw on',
  'Orchestration Layer':           'how their systems connect and share data',
  'Evaluation & Observation Layer':'who owns AI and how they track whether it works',
  'none':                          'no single weak area — all four foundations are even',
  '':                              'their overall foundations',
};
function areaPhrase_(area) {
  return AREA_PHRASE[String(area)] || String(area);
}

// ── Main handler ─────────────────────────────────────────────────────────────

function doPost(e) {
  const raw = (e && e.postData) ? e.postData.contents : '{}';
  let ss = null;

  try {
    ss = SpreadsheetApp.openById(SHEET_ID);
    const data = JSON.parse(raw);

    // ── write_emails: accept email drafts generated by Claude Code ───────────
    if (data.action === 'write_emails') {
      const sheet = ss.getSheetByName(SHEET_NAME);
      const subjectCol = HEADERS.indexOf('Email subject') + 1;
      const bodyCol    = HEADERS.indexOf('Email body')    + 1;
      const emails = Array.isArray(data.emails) ? data.emails : [];
      emails.forEach(function(item) {
        if (!item.rowIndex || !item.subject || !item.body) return;
        sheet.getRange(item.rowIndex, subjectCol).setValue(item.subject);
        sheet.getRange(item.rowIndex, bodyCol).setValue(item.body);
      });
      return jsonResponse({ status: 'ok', written: emails.length });
    }

    // Capture the payload verbatim BEFORE mapping it. The quiz posts with
    // mode:'no-cors' and cannot see our response, so if the mapped write ever
    // fails mid-event this is the only copy of the submission.
    logRaw_(ss, raw);

    const sheet = ss.getSheetByName(SHEET_NAME);
    ensureHeaders_(sheet);

    const row = COLUMNS.map(function (col) {
      const val = data[col];
      return (val !== undefined && val !== null) ? val : '';
    });
    // Pad the manual columns: Email subject, Email body, Email sent?, Notes
    while (row.length < HEADERS.length) row.push('');

    sheet.appendRow(row);

    return jsonResponse({ status: 'ok' });

  } catch (err) {
    // Same blind-spot problem: surface the failure somewhere durable.
    Logger.log('doPost failed: ' + err.message);
    if (ss) logError_(ss, err, raw);
    return jsonResponse({ status: 'error', message: err.message });
  }
}

// ── Durable logging (the mode:'no-cors' blind spot) ──────────────────────────

function logRaw_(ss, raw) {
  try {
    const s = ss.getSheetByName('_raw') || ss.insertSheet('_raw');
    s.appendRow([new Date(), String(raw).slice(0, 45000)]);
  } catch (e) { /* logging must never break the write */ }
}

function logError_(ss, err, raw) {
  try {
    const s = ss.getSheetByName('_errors') || ss.insertSheet('_errors');
    s.appendRow([new Date(), String(err.message), String(err.stack || ''), String(raw).slice(0, 20000)]);
  } catch (e) { /* ignore */ }
}

// ── Sheet shape ──────────────────────────────────────────────────────────────

// Guarantees the sheet is wide enough and its header row matches HEADERS.
// Throws loudly on a mismatch rather than appending skewed rows.
function ensureHeaders_(sheet) {
  const missing = HEADERS.length - sheet.getMaxColumns();
  if (missing > 0) sheet.insertColumnsAfter(sheet.getMaxColumns(), missing);

  if (sheet.getLastRow() === 0) {
    sheet.appendRow(HEADERS);
    styleHeaderRow(sheet);
    return;
  }

  const existing = sheet.getRange(1, 1, 1, HEADERS.length).getValues()[0];
  for (let i = 0; i < HEADERS.length; i++) {
    if (String(existing[i]).trim() !== HEADERS[i]) {
      throw new Error('Header mismatch at column ' + (i + 1) + ' (found "' + existing[i] +
        '", expected "' + HEADERS[i] + '"). Run resetSheet() once from the GAS editor.');
    }
  }
}

// Reads every data row, clamped to the narrower of HEADERS and the actual sheet
// width so a stale sheet can never throw "range exceeds grid limits".
function readAllRows_(sheet) {
  const lastRow = sheet.getLastRow();
  if (lastRow <= 1) return [];
  const width = Math.min(HEADERS.length, sheet.getLastColumn());
  return sheet.getRange(2, 1, lastRow - 1, width).getValues();
}

// ── ONE-TIME MIGRATION (scoring v2) ──────────────────────────────────────────
// Run once from the GAS editor BEFORE redeploying. Archives whatever is in the
// sheet to a timestamped tab, then rewrites the header row to match HEADERS.
// Nothing is destroyed, and it is safe to re-run (archives are timestamped).
function resetSheet() {
  const ss    = SpreadsheetApp.openById(SHEET_ID);
  const sheet = ss.getSheetByName(SHEET_NAME);

  if (sheet.getLastRow() > 0) {
    const copy = sheet.copyTo(ss);
    // Uniquify: two runs in the same minute would otherwise collide on the name.
    let base = 'archive_' + Utilities.formatDate(new Date(), 'Europe/Stockholm', 'yyyyMMdd_HHmm');
    let name = base, n = 2;
    while (ss.getSheetByName(name)) name = base + '_' + (n++);
    copy.setName(name);
    Logger.log('Archived ' + sheet.getLastRow() + ' row(s) to ' + name);
  }

  sheet.clear();
  const missing = HEADERS.length - sheet.getMaxColumns();
  if (missing > 0) sheet.insertColumnsAfter(sheet.getMaxColumns(), missing);
  sheet.appendRow(HEADERS);
  styleHeaderRow(sheet);
  Logger.log('Headers reset: ' + HEADERS.length + ' columns.');
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function jsonResponse(obj) {
  return ContentService
    .createTextOutput(JSON.stringify(obj))
    .setMimeType(ContentService.MimeType.JSON);
}

function styleHeaderRow(sheet) {
  const range = sheet.getRange(1, 1, 1, HEADERS.length);
  range.setFontWeight('bold');
  range.setBackground('#1B3A6B');   // Columbia Road navy
  range.setFontColor('#FFFFFF');
  range.setFontSize(11);
  sheet.setFrozenRows(1);
  sheet.autoResizeColumns(1, HEADERS.length);

  // Highlight the "Email sent?" column in a soft amber so it stands out
  const emailSentCol = HEADERS.indexOf('Email sent?') + 1;
  if (emailSentCol > 0) {
    sheet.getRange(1, emailSentCol).setBackground('#F59E0B');
  }
}

// ── Aggregated results for live dashboard ────────────────────────────────────
// Called by aggregated-results.html via fetch. Returns JSON with CORS headers.

// Zero-filled counter keyed in canonical order, so the dashboard can render an
// empty bucket ("nobody is at Stage 3 yet") and colour by position.
function zeroFilled_(keys) {
  const o = {};
  keys.forEach(function (k) { o[k] = 0; });
  return o;
}

// Blank cells read as '' and Number('') is 0, which would drag every mean down.
// Only genuine numbers get through.
function num_(v) {
  if (v === '' || v === null || v === undefined) return null;
  const n = Number(v);
  return isFinite(n) ? n : null;
}

function median_(arr) {
  if (!arr.length) return null;
  const s = arr.slice().sort(function (a, b) { return a - b; });
  const m = Math.floor(s.length / 2);
  return s.length % 2 ? s[m] : Math.round((s[m - 1] + s[m]) / 2);
}

// Tally a '; '-joined multi-select column.
function tally_(counts, cell) {
  if (!cell) return;
  String(cell).split(';').forEach(function (part) {
    const label = part.trim();
    if (label) counts[label] = (counts[label] || 0) + 1;
  });
}

function doGet(e) {
  try {
    const ss    = SpreadsheetApp.openById(SHEET_ID);
    const sheet = ss.getSheetByName(SHEET_NAME);
    const col   = function (name) { return COLUMNS.indexOf(name); };
    const submittedCol = col('submitted_at');

    // ── action=rows: return participants needing email drafts ────────────────
    // Used by the /generate-emails Claude Code skill — no API key required.
    if (e && e.parameter && e.parameter.action === 'rows') {
      const allData = readAllRows_(sheet);
      const bodyCol = HEADERS.indexOf('Email body');
      const rows = [];
      allData.forEach(function (row, i) {
        if (!row[submittedCol]) return;
        if (row[bodyCol]) return; // draft already exists
        rows.push({
          rowIndex:            i + 2,
          name:                row[col('name')],
          email:               row[col('email')],
          role:                row[col('role')],
          team_size:           row[col('team_size')],
          readiness_score:     row[col('readiness_score')],
          readiness_band:      row[col('readiness_band')],
          stage:               row[col('stage')],
          fit:                 row[col('fit')],
          // Key name kept as weakest_category for the /generate-emails skill.
          // Sourced from the quiz's own weakest_area — may be 'none'.
          weakest_category:    row[col('weakest_area')]   || '',
          strongest_area:      row[col('strongest_area')] || '',
          dims: {
            data_layer:    row[col('data_layer_pct')],
            context_layer: row[col('context_layer_pct')],
            orchestration: row[col('orchestration_layer_pct')],
            eval_obs:      row[col('eval_obs_layer_pct')],
          },
          next_moves:          row[col('next_moves')] || '',
          points_to_next_band: row[col('points_to_next_band')],
          roi:                 row[col('roi_estimate_eur')] || null,
          blockers:            row[col('top_blockers')]     || null,
          roadmap:             row[col('roadmap_headline')] || null,
        });
      });
      return corsJson({ rows: rows });
    }

    // ── Aggregation for the live dashboard ──────────────────────────────────
    const stageDist   = zeroFilled_(STAGE_ORDER);
    const bandDist    = zeroFilled_(BAND_ORDER);
    const fitDist     = zeroFilled_(FIT_ORDER);
    const weakestDist = zeroFilled_(DIM_ORDER.concat(['none']));
    const dimSums     = zeroFilled_(DIM_ORDER);
    const dimCounts   = zeroFilled_(DIM_ORDER);
    const dimColumn   = {
      'Data Layer':                    'data_layer_pct',
      'Context Layer':                 'context_layer_pct',
      'Orchestration Layer':           'orchestration_layer_pct',
      'Evaluation & Observation Layer':'eval_obs_layer_pct',
    };

    const blockerCounts = {};
    const oppCounts     = {};
    const scores = [];
    const rois   = [];
    let total = 0;

    readAllRows_(sheet).forEach(function (row) {
      if (!row[submittedCol]) return;   // skip blank rows
      total++;

      const stage = row[col('stage')];
      if (stage && stageDist.hasOwnProperty(stage)) stageDist[stage]++;

      const band = row[col('readiness_band')];
      if (band && bandDist.hasOwnProperty(band)) bandDist[band]++;

      const fit = row[col('fit')];
      if (fit && fitDist.hasOwnProperty(fit)) fitDist[fit]++;

      const weakest = row[col('weakest_area')];
      if (weakest && weakestDist.hasOwnProperty(weakest)) weakestDist[weakest]++;

      const score = num_(row[col('readiness_score')]);
      if (score !== null) scores.push(score);

      const roi = num_(row[col('roi_estimate_eur')]);
      if (roi !== null && roi > 0) rois.push(roi);

      DIM_ORDER.forEach(function (d) {
        const v = num_(row[col(dimColumn[d])]);
        if (v !== null) { dimSums[d] += v; dimCounts[d]++; }
      });

      tally_(blockerCounts, row[col('top_blockers')]);
      tally_(oppCounts,     row[col('top_opportunities')]);
    });

    const dimMeans = {};
    DIM_ORDER.forEach(function (d) {
      dimMeans[d] = dimCounts[d] ? Math.round(dimSums[d] / dimCounts[d]) : 0;
    });

    return corsJson({
      total: total,
      generated_at: new Date().toISOString(),
      stage_distribution:   stageDist,
      band_distribution:    bandDist,
      fit_distribution:     fitDist,
      dimension_means:      dimMeans,
      weakest_area_counts:  weakestDist,
      readiness: {
        // Median is the headline: one outlier skews the mean on a ~15-person room.
        mean:   scores.length ? Math.round(scores.reduce(function (a, b) { return a + b; }, 0) / scores.length) : null,
        median: median_(scores),
        min:    scores.length ? Math.min.apply(null, scores) : null,
        max:    scores.length ? Math.max.apply(null, scores) : null,
      },
      roi: {
        // No mean — the €1.5M deal-size midpoint makes it wild.
        count:      rois.length,
        median_eur: median_(rois),
        total_eur:  rois.reduce(function (a, b) { return a + b; }, 0),
      },
      top_blockers:      blockerCounts,
      top_opportunities: oppCounts,
    });

  } catch (err) {
    return corsJson({ error: err.message });
  }
}

function corsJson(obj) {
  return ContentService
    .createTextOutput(JSON.stringify(obj))
    .setMimeType(ContentService.MimeType.JSON);
}

// ── Email follow-up configuration ─────────────────────────────────────────────
// PRIMARY approach: use the /generate-emails Claude Code skill — no API key needed.
// ALTERNATIVE (fully automated): set ANTHROPIC_API_KEY in Script Properties and
//   run generateFollowUpEmails() directly from the GAS editor.
// Update MEET_URL to the actual booking link before sending.
const MEET_URL = 'https://calendar.app.google/UixxaEZYnSkbLjSG9';

// ── Generate personalised email drafts (automated alternative) ───────────────
// Run in the GAS editor if you prefer fully automated generation via the API.
// Primary approach: use /generate-emails in Claude Code (no API key required).
function generateFollowUpEmails() {
  const ss    = SpreadsheetApp.openById(SHEET_ID);
  const sheet = ss.getSheetByName(SHEET_NAME);

  const apiKey = PropertiesService.getScriptProperties().getProperty('ANTHROPIC_API_KEY');
  if (!apiKey) { Logger.log('ANTHROPIC_API_KEY not set in Script Properties.'); return; }

  const data = readAllRows_(sheet);
  if (!data.length) { Logger.log('No data rows.'); return; }

  const col          = function (name) { return COLUMNS.indexOf(name); };
  const subjectCol   = HEADERS.indexOf('Email subject');
  const bodyCol      = HEADERS.indexOf('Email body');
  const submittedCol = col('submitted_at');

  data.forEach(function(row, i) {
    if (!row[submittedCol]) return;  // skip empty rows
    if (row[bodyCol]) return;        // skip rows with draft already

    const rowIndex = i + 2;
    const email    = row[col('email')];

    const prompt = emailPrompt_({
      firstName:        String(row[col('name')]).split(' ')[0],
      role:             row[col('role')],
      teamSize:         row[col('team_size')],
      readinessScore:   row[col('readiness_score')],
      band:             row[col('readiness_band')],
      stage:            row[col('stage')],
      fit:              row[col('fit')],
      weakestArea:      row[col('weakest_area')],
      strongestArea:    row[col('strongest_area')],
      nextMoves:        row[col('next_moves')],
      pointsToNextBand: row[col('points_to_next_band')],
      roi:              row[col('roi_estimate_eur')],
      blockers:         row[col('top_blockers')],
      roadmap:          row[col('roadmap_headline')],
    });

    try {
      const draft = callClaude_(prompt, apiKey);
      sheet.getRange(rowIndex, subjectCol + 1).setValue(draft.subject);
      sheet.getRange(rowIndex, bodyCol + 1).setValue(draft.body);
      Logger.log('Draft written for: ' + email);
    } catch (err) {
      Logger.log('Failed for ' + email + ': ' + err.message);
    }

    Utilities.sleep(1200);
  });

  Logger.log('generateFollowUpEmails done.');
}

// One participant object in, one prompt string out. Fields come straight from
// the sheet columns — the quiz already computed weakest/strongest area and the
// recommended next moves, so nothing is re-derived here.
function emailPrompt_(p) {
  const FIT_GLOSS = {
    ahead:     'their foundations are in better shape than what they actually have running — they can move now without more prep',
    matched:   'their foundations and what they have running are in step',
    stretched: 'they are running ahead of their foundations, so output reliability is the risk',
  };

  const weakest  = areaPhrase_(p.weakestArea);
  const isBalanced = String(p.weakestArea) === 'none' || !p.weakestArea;

  const fitLine       = p.fit ? '\n- Foundations vs what is live: ' + p.fit +
                                (FIT_GLOSS[p.fit] ? ' — ' + FIT_GLOSS[p.fit] : '') : '';
  const strongestLine = p.strongestArea ? '\n- Strongest foundation: ' + areaPhrase_(p.strongestArea) : '';
  const movesLine     = p.nextMoves ? '\n- Suggested next moves (shown to them on screen): ' + p.nextMoves : '';
  const blockersLine  = p.blockers ? '\n- Top blockers: ' + p.blockers : '';
  const roiLine       = p.roi ? '\n- ROI estimate: €' + p.roi : '';

  // A balanced result has no weak area to write about — pivot to the fit story.
  const focusNote = isBalanced
    ? '- 1 paragraph: no single foundation is lagging, so focus on what ' + (p.fit || 'their situation') +
      ' means for their next step, and name one specific action\n'
    : '- 1 paragraph on ' + weakest + ': what the gap means and one specific action to take\n';
  const blockersNote = p.blockers
    ? '- 1-2 sentences on their biggest blocker with a concrete counter-move\n'
    : '';
  const roiNote = p.roi
    ? '- 1 sentence: "Based on your inputs, the opportunity is around €' + p.roi + '."\n'
    : '';

  return 'Write a personalised follow-up email from Columbia Road after an AI maturity ' +
    'assessment event in Stockholm. Tone: direct, specific, no filler — a sharp consultant ' +
    'speaking plainly, not a content generator producing balanced feedback. Target ~220 words. ' +
    'Return ONLY a valid JSON object with two string fields: "subject" and "body". ' +
    'No markdown fences, no other text.\n\n' +
    'Note on the two scores: "readiness" measures their foundations (data, ownership, ' +
    'connected tools, team habits) out of 100. "Stage" is separate — it is what they ' +
    'actually have running today. The two can disagree, which is the interesting part.\n\n' +
    'Participant:\n' +
    '- Name: ' + p.firstName + '\n' +
    '- Role: ' + p.role + '\n' +
    '- Team size: ' + p.teamSize + '\n' +
    '- Readiness score: ' + p.readinessScore + '/100 (' + p.band + ')\n' +
    '- Stage (what is actually live): ' + p.stage +
    fitLine +
    '\n- Weakest foundation: ' + weakest +
    strongestLine +
    movesLine +
    blockersLine +
    roiLine + '\n' +
    '- Roadmap headline: ' + p.roadmap + '\n\n' +
    'Email structure (in this order):\n' +
    '- Subject: "Your AI readiness score — [short stage label]"\n' +
    '- "Hi ' + p.firstName + ',"\n' +
    '- 2-3 sentences: their readiness score and stage, one concrete implication for their role/team size\n' +
    focusNote +
    blockersNote +
    roiNote +
    '- Closing: reference the roadmap headline (' + p.roadmap + ') then: ' +
    '"If you want to talk through where to start, book a slot: ' + MEET_URL + '"\n' +
    '- Sign off: "Columbia Road"\n\n' +
    'Return only the JSON object — nothing else.';
}

function callClaude_(prompt, apiKey) {
  const resp = UrlFetchApp.fetch('https://api.anthropic.com/v1/messages', {
    method: 'post',
    headers: {
      'x-api-key':         apiKey,
      'anthropic-version': '2023-06-01',
      'content-type':      'application/json',
    },
    payload: JSON.stringify({
      model:      'claude-opus-5',
      max_tokens: 1024,
      messages:   [{ role: 'user', content: prompt }],
    }),
    muteHttpExceptions: true,
  });

  if (resp.getResponseCode() !== 200) {
    throw new Error('API ' + resp.getResponseCode() + ': ' + resp.getContentText());
  }

  const result = JSON.parse(resp.getContentText());
  var text = result.content[0].text.trim();
  text = text.replace(/^```(?:json)?\s*/i, '').replace(/```\s*$/, '').trim();
  return JSON.parse(text);
}

// ── Send reviewed drafts ───────────────────────────────────────────────────────
// Run after reviewing the Email body column. Sends rows with a draft but no sent timestamp.
function sendFollowUpEmails() {
  const ss    = SpreadsheetApp.openById(SHEET_ID);
  const sheet = ss.getSheetByName(SHEET_NAME);

  const data = readAllRows_(sheet);
  if (!data.length) { Logger.log('No data rows.'); return; }

  const emailCol     = COLUMNS.indexOf('email');
  const submittedCol = COLUMNS.indexOf('submitted_at');
  const subjectCol   = HEADERS.indexOf('Email subject');
  const bodyCol      = HEADERS.indexOf('Email body');
  const sentCol      = HEADERS.indexOf('Email sent?');

  let sent = 0;

  data.forEach(function(row, i) {
    if (!row[submittedCol]) return;  // empty row
    if (!row[bodyCol]) return;       // no draft yet
    if (row[sentCol]) return;        // already sent

    const rowIndex  = i + 2;
    const recipient = row[emailCol];
    const subject   = row[subjectCol];
    const body      = row[bodyCol];

    try {
      GmailApp.sendEmail(recipient, subject, body, { name: 'Columbia Road' });
      sheet.getRange(rowIndex, sentCol + 1).setValue('Sent · ' + new Date().toISOString());
      Logger.log('Sent: ' + recipient);
      sent++;
    } catch (err) {
      Logger.log('Error sending to ' + recipient + ': ' + err.message);
    }
  });

  Logger.log('sendFollowUpEmails done. Sent: ' + sent);
}

// ── Test helpers ─────────────────────────────────────────────────────────────
// Editor-only. Never reached by doPost/doGet. Run these BEFORE redeploying:
// editor runs use the saved code immediately, while the /exec endpoint keeps
// serving the last deployed version.

function testSetup() {
  const ss    = SpreadsheetApp.openById(SHEET_ID);
  const sheet = ss.getSheetByName(SHEET_NAME);
  Logger.log('Sheet found: ' + sheet.getName());
  Logger.log('Last row: '    + sheet.getLastRow());
  Logger.log('Columns: ' + COLUMNS.length + ' data + 4 manual = ' + HEADERS.length + ' headers');
  if (COLUMNS.length + 4 !== HEADERS.length) Logger.log('FAIL: COLUMNS/HEADERS out of step');
}

// Cells that must never be blank on a real submission. Excludes next_moves
// (empty at the top band), points_to_next_band and roi_estimate_eur (both
// legitimately empty), and stage_index (legitimately 0).
const REQUIRED_SCORING_COLS = [
  'readiness_score', 'readiness_band', 'stage', 'fit',
  'data_layer_pct', 'context_layer_pct', 'orchestration_layer_pct', 'eval_obs_layer_pct',
  'weakest_area', 'strongest_area',
];

// Five varied submissions, so every distribution gets spread. Without variation
// the donut renders one 360° segment and the multi-arc path never runs.
function testPost_v2() {
  const VARIANTS = [
    { stage_index: 0, stage: STAGE_ORDER[0], readiness_score: 21, readiness_band: BAND_ORDER[0], fit: 'matched',
      data_layer_pct: 25, context_layer_pct: 25, orchestration_layer_pct: 25, eval_obs_layer_pct: 25,
      weakest_area: 'none',                         strongest_area: 'Evaluation & Observation Layer', roi_estimate_eur: null },
    { stage_index: 1, stage: STAGE_ORDER[1], readiness_score: 30, readiness_band: BAND_ORDER[1], fit: 'matched',
      data_layer_pct: 42, context_layer_pct: 25, orchestration_layer_pct: 20, eval_obs_layer_pct: 67,
      weakest_area: 'Orchestration Layer',          strongest_area: 'Evaluation & Observation Layer', roi_estimate_eur: 240000 },
    { stage_index: 1, stage: STAGE_ORDER[1], readiness_score: 38, readiness_band: BAND_ORDER[2], fit: 'matched',
      data_layer_pct: 50, context_layer_pct: 33, orchestration_layer_pct: 40, eval_obs_layer_pct: 33,
      weakest_area: 'Context Layer',                strongest_area: 'Data Layer',                     roi_estimate_eur: 610000 },
    { stage_index: 3, stage: STAGE_ORDER[3], readiness_score: 44, readiness_band: BAND_ORDER[3], fit: 'stretched',
      data_layer_pct: 58, context_layer_pct: 42, orchestration_layer_pct: 33, eval_obs_layer_pct: 67,
      weakest_area: 'Orchestration Layer',          strongest_area: 'Evaluation & Observation Layer', roi_estimate_eur: 1850000 },
    { stage_index: 2, stage: STAGE_ORDER[2], readiness_score: 54, readiness_band: BAND_ORDER[4], fit: 'ahead',
      data_layer_pct: 75, context_layer_pct: 58, orchestration_layer_pct: 60, eval_obs_layer_pct: 100,
      weakest_area: 'Context Layer',                strongest_area: 'Evaluation & Observation Layer', roi_estimate_eur: 380000 },
  ];

  VARIANTS.forEach(function (v, i) {
    const payload = {
      submitted_at: new Date().toISOString(),
      name: 'Test Person ' + (i + 1),
      email: 'test' + (i + 1) + '@example.com',
      role: 'Sales leadership',
      team_size: '10–50',
      points_to_next_band: 8,
      next_moves: 'B1: Clear out duplicates | C1: Put one name against AI',
      deal_size: '€50K–€200K',
      close_rate: '20–35%',
      admin_time: '20–40%',
      monthly_leads: '200–1K',
      lead_to_conv: '5–15%',
      sales_process_docs: 'Yes but stale',
      ai_tools: 'AI assistants (Copilot/ChatGPT)',
      ai_agents: 'Ran a pilot or experiment',
      ai_integration: 'Basic automations',
      ai_scalability: 'We use AI features inside each tool but they are not connected',
      data_quality: 'Centralised but dirty',
      knowledge_source: 'Scattered docs and wikis',
      governance_owner: 'Each team runs their own',
      sales_ai_contribution: 'Sales gives needs and reviews output',
      team_attitude: 'Curious but cautious',
      top_opportunities: 'Qualifying leads faster; Researching accounts & competitors',
      top_blockers: "Our data is a mess; We can't prove the ROI",
      biggest_time_waste: 'CRM hygiene',
      roadmap_headline: 'Ship one agent by Q4',
    };
    for (const k in v) payload[k] = v[k];

    const res = doPost({ postData: { contents: JSON.stringify(payload) } });
    Logger.log('POST ' + (i + 1) + ': ' + res.getContent());
  });

  assertLastRowsPopulated_(VARIANTS.length);
}

// Reads back the rows just written and fails loudly on any blank scoring cell.
function assertLastRowsPopulated_(n) {
  const ss    = SpreadsheetApp.openById(SHEET_ID);
  const sheet = ss.getSheetByName(SHEET_NAME);
  const last  = sheet.getLastRow();
  if (last < n + 1) { Logger.log('FAIL: expected at least ' + n + ' data rows, found ' + (last - 1)); return; }

  const rows = sheet.getRange(last - n + 1, 1, n, HEADERS.length).getValues();
  let bad = 0;
  rows.forEach(function (row, r) {
    REQUIRED_SCORING_COLS.forEach(function (name) {
      // 0 is a legitimate percentage — test for '' specifically, not falsiness.
      if (row[COLUMNS.indexOf(name)] === '') {
        Logger.log('FAIL: row ' + (last - n + 1 + r) + ' has blank "' + name + '"');
        bad++;
      }
    });
  });
  Logger.log(bad === 0
    ? 'PASS: ' + n + ' row(s) written, every scoring cell populated.'
    : 'FAIL: ' + bad + ' blank scoring cell(s).');
}

function testDoGet() {
  Logger.log(doGet({ parameter: {} }).getContent());
}

function testRows_() {
  Logger.log(doGet({ parameter: { action: 'rows' } }).getContent());
}

// Prints the prompt for the most recent row without calling the API.
function testEmailPrompt() {
  const ss   = SpreadsheetApp.openById(SHEET_ID);
  const data = readAllRows_(ss.getSheetByName(SHEET_NAME));
  if (!data.length) { Logger.log('No data rows.'); return; }
  const row = data[data.length - 1];
  const col = function (name) { return COLUMNS.indexOf(name); };
  Logger.log(emailPrompt_({
    firstName:        String(row[col('name')]).split(' ')[0],
    role:             row[col('role')],
    teamSize:         row[col('team_size')],
    readinessScore:   row[col('readiness_score')],
    band:             row[col('readiness_band')],
    stage:            row[col('stage')],
    fit:              row[col('fit')],
    weakestArea:      row[col('weakest_area')],
    strongestArea:    row[col('strongest_area')],
    nextMoves:        row[col('next_moves')],
    pointsToNextBand: row[col('points_to_next_band')],
    roi:              row[col('roi_estimate_eur')],
    blockers:         row[col('top_blockers')],
    roadmap:          row[col('roadmap_headline')],
  }));
}
